name: Build

on:
  push:
    branches:
    - master
    - dev
    - feature/*
  pull_request:
    branches:
    - master
    - dev
    - feature/*

jobs:
  build:
    name: Build with ${{ matrix.configuration }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    
    strategy:
      fail-fast: false
      matrix:
        configuration:
        - Debug
        - Release
        platform:
        - windows-latest
        - ubuntu-latest
        - macos-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Build source code
      run: dotnet build EShop.sln -c ${{ matrix.configuration }}